Add displayUserInfo dom update
ericahagle/fitlit pull request #47
Opened 2023-10-16 16:55 UTC by BrendanTurner1

# Description
This function will update the webpage with the current user's basic info

# Contributors
@BrendanTurner1 

# Screenshot(s)
Currently not working

# Notes
Does not work. Thinking the script is not being properly connected to the HTML

# Checklist
- [x] My PR has an appropriately descriptive and concise title.
- [x] My PR denotes any/all team members who contributed to it.
- [x] My code follows the Turing Style Guides and best practices.
- [x] I ran the code locally and verified that there are no visible errors.
- [x] feat: My PR clearly describes what feature I'm adding and any changes needed to make it work. _(if applicable)_
- [ ] fix: My PR clearly describes what bug I'm fixing and why. _(if applicable)_
- [ ] refactor: My PR clearly describes what code I'm refactoring and why. _(if applicable)_
- [ ] docs: My PR clearly describes which doc(s) I'm updating and why. _(if applicable)_

2023-10-16 21:27 UTC, ericahagle commented
@BrendanTurner1 Would you please link the ticket this relates to? (In the 'Development' section under 'Milestone' on the sidebar)

2023-10-16 21:42 UTC, tenthwalker approved these changes
looks good to me, we found that we had to be running the server to get the CSS to work so that may be the necessary fix to get this working as well

2023-10-16 21:45 UTC, ericahagle requested changes

2023-10-16 21:45 UTC, ericahagle commented on src/domUpdates.js
>  //Here are 2 example functions just to demonstrate one way you can export/import between the two js files. You'll want to delete these once you get your own code going.
@BrendanTurner1 We should probably go ahead and get rid of these example functions now, since we're starting to add our real ones, yeah?

2023-10-17 20:27 UTC, ericahagle approved these changes
Tested on my local and it looks great! Good work, @BrendanTurner1 ! 🍨

2023-10-17 20:27 UTC, merged